---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    io.kompose.service: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"