apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-1
  labels:
    io.kompose.service: postgres
    tier: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi